### ISSUE TITLE
Review Linux build PRs

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#1076]
Review and merge Michael Hart's Linux build work

**Comment by FreddieAkeroyd** [comment]
- [ ] ISISComputingGroup/EPICS-extensions#1
- [ ] ISISComputingGroup/EPICS-inst_servers#34
- [ ] ISISComputingGroup/EPICS-IocLogServer#1
- [ ] ISISComputingGroup/EPICS-CSS#2
- [ ] ISISComputingGroup/EPICS#10
