### ISSUE TITLE
ENGIN-X / IMAT: Instron (Stress Rig): Test IOC with real hardware

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#2338]
The EPICS IOC for the Instron stress rig will need to be tested against real hardware on either ENGIN-X or IMAT.

The stress rig is quite complicated so it would be best to test it with plenty of time before it is required, so that we have a reasonable opportunity to fix any issues which crop up.

This ticket requires tickets #2111, #2112, #2113 and #2115 to be done. Ticket #2114 would be helpful but the rig can be tested without it.

If any differences are found between the emulator and the real device, modify the emulator so that the device is properly simulated.

**Comment by kjwoodsISIS** [comment]
The Stress Rig has its own control PC.  The Stress Rig PC is fitted with a GPIB card.  IBEX does not talk directly to the Stress Rig, it talks to the Stress Rig PC.

Mounting the Stress Rig on the ENGIN-X sample stack prior to testing it presents some significant problems:
1. It takes time (if the Stress Rig is not already on the sample stack).
1. The Stress Rig is a large items of equipment.  It needs to be moved carefully to avoid damaging other equipment.
1. Even when mounted on the sample stack, there is a risk that the Stress Rig could collide with other items when it is moved.
If we can avoid having to make wholesale movements (i.e. translate or rotate) of the Stress Rig during testing, so much the better.

There are at least two ways to test the Stress Rig IOCs with the Stress Rig without have to move the Stress Rig itself:
   1. There is a spare Stress Rig PC.  So, we can do the following:
      1. set up the spare Stress Rig PC (but not connected to the Stress Rig).
      1. connect the spare Stress Rig PC to a GPIB-Ethernet box (rather like a MOXA, but for GPIB).
      1. IBEX can use EPICS to communicate with the spare Stress Rig PC.
   1. Connect to the Stress Rig (without mounting it on the Sample Stack)
      1. ask the instrument scientists to place the spare Stress Rig (and its PC) outside the ENGIN-X blockhouse (it will need to be cordoned off)
      1. connect the spare Stress Rig PC to a GPIB-Ethernet box
      1. IBEX can use EPICS to communicate with the spare Stress Rig.
      1. This test might be best performed at the ENGIN-X blockhouse, so that you can see the Stress Rig respond to commands.

**Comment by ChrisM-S** [comment]
This may be me being out of date, but unless something has changed, the Stress rig PC used to be just used for collecting data on offline experiments and when the stress rig was on the beamline NDXENGINX connected directly via the GPIB-ENET box to the stress rig to cut out the middle-man PC (also via a cutout cable for safety purposes).  If it has changed, what protocol does NDXENGINX use to talk to the stress rig PC currently? And out of interest what are the stress rig PCs called – I guess we don’t support them... (or do we?)

**Comment by KathrynBaker** [comment]
The towers we talk to via GPIB is what is being referred to here, not a PC in the traditional sense. It is a tower, it is a computer, it cannot be put on a network directly (hence GPIBs)

This is simply a nomenclature confusion – don’t worry about it Chris nothing has actually changed from how we interact with anything.

**Comment by Tom-Willemsen** [comment]
Can communicate with the device and get data back, but I'm getting occasionally disconnected by the device when using a modified IOC that only asks for Position/Stress/Strain values. Looking at this with @FreddieAkeroyd we think that it's an issue with Visa/Asyn drivers timing out. Ticket #2416 might help with this once it's complete but isn't solving the problem yet.

I tried simplifying the IOC even further to only ever ask for Position values (at a one second scan rate), and the same error occurs occasionally (but takes ~3 times longer to occur than with three channels, as one might expect).

The error text is `2017/06/14 08:56:53.886458 L0 TE:NDW1799:INSTRON_01:POS:RAW: write failed because connection was closed by device`.

**Comment by ChrisM-S** [comment]
Don’t know if you’ve tried but it may be worth looking at the VISA traffic with NISpy which will show exactly what is going back and forwards in terms of VISA calls.

**Comment by FreddieAkeroyd** [comment]
Hi Chris, we were using NISpy yesterday and that was helpful - highlighed the timeout, but would have been even more helpful if the NIspy interface told you the actual visa call parameter values correctly!

**Comment by FreddieAkeroyd** [comment]
I believe the disconnections are being actioned by the IOC itself due to a read error, which we though were just timeouts but may be more to it. We don't see the read error printed as I think the closeConenction call in the IOC overwrite the error message, so we just see the next write fail as I think asyn manages auto connections in a separate thread and hence if the next write occurs too quickly it will fail. #2416 fixes this error printing issue as well as giving a few more options to examine.

**Comment by FreddieAkeroyd** [comment]
maybe close connection on every read failure is a bit harsh...

**Comment by FreddieAkeroyd** [comment]
Our original bus timeouts were caused by reading with an immediate timeout, which GPIB-ENET didn't like. Having allowed this to be requested to be say 10ms, there was a second place where a read with zero timeout was being done and that was on asyn internally clearing the input buffer. Enforcing the same specified timeout (10ms seems to be OK) at this point clears the error. It looks like the stress rig is fine being checked for data, it is just something in visa about the zero timeout on the read? (maybe it can't check the device that quickly every time - it works 9/10 times).

**Comment by Tom-Willemsen** [comment]
The parts of the IOC written in #2111 and #2112 have been tested against the real hardware and appear to work in the same way as the existing LabVIEW driver.

There are minor changes to the rig's setup in a pull request for this ticket - Mostly these are GPIB setup issues, but there was also an issue that the timeouts needed to be increased to ~1 second because the rig is occasionally slow to respond. This is the same timeout that LabVIEW uses.

TODO:
- [ ] Test commands in #2213 (waveform commands) once that ticket is complete.
- [ ] Go down to ENGINX and check that the rig is physically responding as the scientists expect. Will require help from the ENGINX scientists to do this. It might be easier to do this when the rig is actually in position and in a state where all the expected commands can be executed.

**Comment by Tom-Willemsen** [comment]
Meeting on ENGINX scheduled for 23/6 as an initial attempt to get simple stress/strain/position control.

**Comment by Tom-Willemsen** [comment]
Went down to Engin-X with Gareth this afternoon.

Was able to action a move to a position setpoint successfully (once), but we had some issues with getting the stress rig to "take" the new setpoint a lot of the time.

I think this boils down to `INSTRON_01:POS:SCALE` containing a value of 0 while the record is active (i.e. `PACT=1`). Currently looking for the best way to ensure that this doesn't happen.

**Comment by Tom-Willemsen** [comment]
Marking as impeded until the tickets in the title are completed - this will give us a useful amount of new functionality to test rather than having to go down to ENGIN-X several more times as the different tickets are completed.

**Comment by John-Holt-Tessella** [comment]
Joe and Saurabh  would like to test the interface with us.

**Comment by Tom-Willemsen** [comment]
Ticket 2113 is merged, this is no longer impeded.

**Comment by Tom-Willemsen** [comment]
Went down to ENGIN-X this afternoon:

Good things:
- The driver talked successfully
- The numbers in the IOC were correct 
- I can set setpoints on the device reliably (this caused problems last time)
- I can tell the device to move to a position, and it moves to the correct position

Bad things:
- The hydraulics are tripping as soon as it reaches the setpoint. It's not 100% clear whether this same issue was happening with the LabVIEW driver - need to double check this.
  * I had a look at the commands being sent from the IOC (to the emulator back at the office). There aren't any special commands sent when the rig reaches the setpoint. 
  * This leads me to suspect that there might be some hardware configuration causing this issue. 
  * @KathrynBaker suggested that low hydraulics pressure could potentially cause this type of issue but not sure. Need to check this.
- Getting errors of the following form. I'm not sure how to fix these other than restarting the whole computer `GPIB0::3::INSTR: viClear The resource is valid, but VISA cannot currently access it. L0 -1 autoConnect could not connect`
  * Having done a bit more research this might be because LabVIEW doesn't release the VISA port properly?
  * According to this page: http://digital.ni.com/public.nsf/websearch/6807113B057FDE4C86256B41008212ED?opendocument&Submitted&&node=133020_US the default behaviour is not to release the serial port
  * Neither closing LabVIEW nor restarting the IBEX server seemed to "free" this port from use.
  * Restarting the computer *does* free the port from use (but is rather inelegant to say the least)

Untested things:
- Waveform generator

---

**TODO next time going down to ENGIN-X**
- [ ] Thoroughly test under what conditions the hydraulics trip. If the behaviour in SECI and IBEX is the same, then we should figure out why it is tripping. If the behaviour is different, figure out what IBEX is sending which is causing issues that LabVIEW isn't.
- [ ] Test the waveform generator

**Comment by Tom-Willemsen** [comment]
Note also, the scientist (Saurabh) has told us that we are welcome to go down to ENGIN-X without them to test the rig, as long as we warn/check with them first.

**Comment by Tom-Willemsen** [comment]
Went back down to Engin-X this morning.

- Waveform commands have been tested and appear to work - we generated sinusioidal and square waves on the position channel which reported correctly on the IOC, and we could see the piston moving in the correct way.
- The issue with hydraulics tripping has been narrowed down to the IOC sending the `P909,0` command. 
  * Command `P909,0` switches the rig back into front panel control mode.
  * If I disable this command in the protocol file the device never trips. 
  * It doesn't matter whether I send this command as part of the normal IOC operation or as an arbitrary command - it trips the rig in either case.
  * I tried sending this command via LabVIEW as an arbitrary command - it didn't trip the hydraulics

**Next steps**
Figure out why the IOC's `P909,0` command causes issues. Could this be a timing thing, i.e. sending `P909,0` too soon after the previous command?

**Comment by ChrisM-S** [comment]
I don’t suppose it’s because the console itself resets the period for the actuator keep-alive timer to a shorter period (than the IOC does) when it gets control?

I can’t remember when/how often the keep alive timer interval is set from LabVIEW now.  My memory is that it was good to set it to its maximum, but it could be that it gets reset to max after every command in the VI just to ensure control doesn’t get lost.

**Comment by Tom-Willemsen** [comment]
@ChrisM-S yes, I do think it's entirely possible that it's related to the watchdog. The way you "poke" it is to send the `C904,0` command. By default the timeout of the watchdog is 3 seconds, the IOC should be poking it at a 1 second interval.

I'm currently having a look at the NISpy logs to see if I can spot any differences between the LabVIEW and EPICS drivers, in terms of either the timings of commands or any other clues...

I did try increasing the watchdog timeout via `C903` while I was on ENGIN-X but this didn't help

**Comment by ChrisM-S** [comment]
I don’t know how the console works, but I’m speculating that as a client of the main box of tricks just like we are, it might be able do a C903 of its own to some much shorter time period which it is happy to guarantee.  Doing a query from the EPICS or LabVIEW side some time later would almost certainly return the 3 second setting (assuming we change it to that regularly at some point in the IOC or VI on startup).

It might be that the only way to check this is to edit the IOC never to set the timeout (just for testing), then allow the console to gain control and then read the timeout back and see if it is now at a different value (once the console has had control and the actuator has bombed out again!).

**Comment by Tom-Willemsen** [comment]
Stress rig now tested on ENGIN-X and working! The issue was that we had to turn off the watchdog every time we entered computer control mode. Previously we were only turning off the watchdog every second.

Found a very minor bug in the waveform generator: if the cycles is already at the maximum, have to press "start waveform" twice to actually start it. I will fix this against the emulator. 

Will also email scientists to see if they want to test it with a sample before cycle start.

**Comment by Tom-Willemsen** [comment]
Pull requests:
- https://github.com/ISISComputingGroup/EPICS-IOC_Test_Framework/pull/23
- https://github.com/ISISComputingGroup/EPICS-instron/pull/3
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/154
- https://github.com/ISISComputingGroup/EPICS-DeviceEmulator/pull/35

Review:
- [ ] Check that IOC tests still pass
- [ ] Check that modifications look sensible
- [ ] Check that there is some basic setup documentation and "gotchas" on the wiki in an appropriate place.

I don't think it's necessary for the reviewer to go down to Engin-X and test this.
