### ISSUE TITLE
Script Server: Releasable Prototype (NICOS)

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#2538]
This is an umbrella ticket to get us to the point where a script server prototype can be released to instruments. In priority order:

- [x] [Integrate the proxy with NICOS core](https://github.com/ISISComputingGroup/IBEX/issues/2539)
- [x] [Provide feedback on the NICOS queue](https://github.com/ISISComputingGroup/IBEX/issues/2540)
- [x] [Receive console output of currently running script](https://github.com/ISISComputingGroup/IBEX/issues/2541)
- [x] [Provide line by line feedback](https://github.com/ISISComputingGroup/IBEX/issues/2149)
- [x] [Allow control of current script](https://github.com/ISISComputingGroup/IBEX/issues/2542)
- [x] [Lock script server access to localhost](https://github.com/ISISComputingGroup/IBEX/issues/2543)
- [x] [Allow control of the script queue](https://github.com/ISISComputingGroup/IBEX/issues/2544)

Once these are done https://github.com/ISISComputingGroup/IBEX/issues/1383 can be done

**Comment by Tom-Willemsen** [comment]
#1383 can (and should) be done now as the above are complete.
