### ISSUE TITLE
Tech debt: CI and deployment stand down [Timebox: 1d]

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2725]
# User story

As an instrument scientist, I would like the integration and deployment of IBEX to be quick and reliable so that I can receive program updates more frequently than once a cycle with a low risk of downtime so that I don't have to wait as long for new features to be delivered and so that the development team have more time to spend on the features I want.

# Background

As discussed at the October sprint retrospective, there are many project areas that we feel deserve attention to improve technically. However, the associated tickets individually do not have sufficiently high priority to have hope of being addressed under our current prioritisation system. As a team, we recognise that in spite of this, the overall long-term health of the project requires addressing technical debt and improving the underlying infrastructure.

As a result of the retrospective, we agreed to try and have a stand down each sprint, beginning in the December 2017 sprint, to address identified key areas.

The first of these sprints had broad consensus to look at our build and deployment systems.

#  Goals

- Divest build knowledge from Matt Clarke about the build system before his departure
- Improve the speed of our Jenkins builds
- Improve the reliability of our Jenkins builds
- Reduce the deployment time for a clean version of IBEX
- Reduce the deployment time for IBEX upgrades

# Tickets

Subject to the above goals, we have identified the following tickets that fall into the scope of the stand down. These have been arranged in rough order of priority. The focus of the list is to improve our existing infrastructure and processes.

- [x] #2504: Move EPICS build to use pipelines
- [x] #2513: Create IBEX utilities repo
- [x] #2429: Automate current deployment workflow preparatory steps
- [x] #2430: Automate installation of IBEX apps
- [x] #2431: Automate post-installation steps
- [x] #2432: Unify the automated deployment workflow
- [ ] #2128: Improve deployment strategy for the dataweb
- [x] #2670 Check OPI script doesn't check labels correctly
- [ ] #1998 Add OPI format checker to Jenkins
- [x] #1912: System tests should get the latest version of genie_python
- [ ] #2774: Eliminate race conditions in setting PV values in IOC test framework
- [x] #2708: genie_python system test framework
- [ ] #2558: Create separate build for MSIs
- [ ] #2320: Improve EPICS build dependencies
- [ ] #2714: Speed up msi/git repo creation
- [x] #2494: Tidy release files
- [ ] #2733: Documentation in CI
- [ ] #2532: Fix making the documentation
- [ ] #731: Make GUI independent of Python distribution?
- [ ] #1046: Build inst_server PRs
- [ ] #1960: Add SHA to genie_python version
- [ ] #1472: Parallel make

# Additional tasks

In addition to the above. The following tasks have been identified as useful:

- [ ] Go through the client build system with Matt and document his knowledge before he leaves
- [ ] Profile our current build systems to identify where the major bottlenecks are
- [ ] Improve the reliability of our existing system tests

# Rules

This ticket will be time-boxed to 1 day. It should not impact the sprint outside of a day.

The person who picks up a ticket is responsible for ensuring that it is completed by the end of the day. That is, they should:

- Ensure that sufficient testing resource is available for the ticket to be cleared by the end of the day
- Action the ticket
- Clearly document their work so that it can be reviewed easily

**Comment by Tom-Willemsen** [comment]
Scheduled for 22nd Nov.

**Comment by AdrianPotter** [comment]
Waiting for #2513 and #2504 to close

**Comment by AdrianPotter** [comment]
A good number of tickets done. #2504 is still outstanding but will be completed via the normal workflow
