### ISSUE TITLE
Eclipse 4: January/February 2018

### ISSUE THREAD

**Issue by AdrianPotter** [ISISComputingGroup/IBEX#2861]
As an IBEX architect, I would like the migration of IBEX to ECLIPSE 4 to continue so that we can eventually change over to take advantage of an up-to-date version of CSS.

Pick up where #2812 leaves off

**Comment by ThomasLohnert** [comment]
I have now created individual tickets for items from the E4 TODO list (you can find everything by searching the backlog for "E4"). 

These tickets were created after sprint planning and are not properly prioritized and labeled with effort etc. I will just link some suggested tickets below to emulate the previous approach taken with suggesting changes in the E4 umbrella ticket. From the next sprint onwards we will not need the umbrella ticket anymore and can propose them individually as we would any other ticket.

Proposed issues (see how far you can get):
- [ ] [E4: Scripting perspective](https://github.com/ISISComputingGroup/IBEX/issues/2876)
- [ ] [E4: Get genie_python talking to PVs](https://github.com/ISISComputingGroup/IBEX/issues/2882)
- [ ] [E4: Re-implement label showing active configuration](https://github.com/ISISComputingGroup/IBEX/issues/2873)
- [ ] [E4: Fix graphs in beam status view](https://github.com/ISISComputingGroup/IBEX/issues/2878)
- [ ] [E4: Preference Menu](https://github.com/ISISComputingGroup/IBEX/issues/2871)

**Comment by AdrianPotter** [comment]
E4 issues will be handled independently of sprint tickets from now on
