### ISSUE TITLE
INES: Prepare to Migrate to IBEX

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3445]
As a developer, I want to complete the preparatory steps prior to migrating INES to use the IBEX instrument control system.

#### Acceptance Criteria
1.  [x] Facilities IT have confirmed they will create a private network on INES 
1.  [x] NDXINES has sufficient free disk space to install IBEX 
1.  [x] IBEX has support for the devices used on INES 
1.  [x] The version of the ICP program on INES has been checked 
1.  [x] Configuration files matching the current SECI config files used on INES are created 
1.  [x] ~INES scripts are converted to genie_python~ (Instrument Scientists will do this)
1.  [ ] INES configuration files and genie_python scripts are tested on a test instance of IBEX

#### Notes
1. The devices on INES are listed on the [INES Instrument Details](https://github.com/ISISComputingGroup/IBEX/wiki/INES-Instrument-Details) list
1. Use the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page to guide you through the migration process. The following activities need to be completed as part of the migration process:
- [x] Ask Facilities IT (Anthony Shuttle) to create a private network for INES.  This is required so that we can use TCP/IP to communicate with the Galils. Facilities IT will need notice of about 4-6 weeks.
   -  [INES VLAN settings](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/INES/INES_VLAN_Settings.txt)
- [x] Check that NDXINES has sufficient disk space to install IBEX
  * INES currently has 83-Gb of free space, but they are also getting a new control PC before the shutdown. Disk space should not be a concern
- [x] Check whether INES uses 5- or 8- digit run-numbers
   - [ ] If it uses 5-digit run-numbers, plan to upgrade the ICP program (to permit 8-digit run-numbers)
   - (uses 5-digit run numbers, ICP upgrade needed)
- [ ] Create a virtual instrument for testing purposes
   - [ ] Set up a test system, NDXINESTEST.
   - [x] create IBEX configurations to correspond to their SECI equivalents
   - [ ] create genie-python scripts to correspond to their Open-Genie equivalents
   * consult with scientists as you do this (see the [Migrate-an-Instrument-Control-PC](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Migrate-an-Instrument-Control-PC) page).
   - [ ] test these configurations & scripts
   - [x] check that all the devices previously supported by SECI (on INES) are supported by IBEX
- [x] arrange one or more training sessions with the scientists to help them understand how to use IBEX
   * Done!  Training arranged for 1st November 2018.

#### Sub-Tickets (for tracking purposes):
Requires #3523
Requires #3524
Requires #3525
Requires #3576
Requires #3577
Requires #3579
Requires #3580

**Comment by John-Holt-Tessella** [comment]
Mantid blocks:

> INES don't use mantid so that won't bother us.

**Comment by ThomasLohnert** [comment]
Configs to migrate: https://github.com/ISISComputingGroup/IBEX/wiki/INES-Instrument-Details#ines-seci-configs

**Comment by DominicOram** [comment]
We should also add a block to cover https://github.com/ISISComputingGroup/IBEX/issues/3524

**Comment by ThomasLohnert** [comment]
Antonella said she would be attempting to write her own genie_python scripts and contact us if she needs help.

**Comment by ThomasLohnert** [comment]
I am away from now, did not have time to run through everything on the test machine myself unfortunately and will not be back until shutdown starts. I have tested it all on my dev machine though and have set up NDXTEST2.

To review: Check the configs on the INES branch:
- [ ] Confirm configurations equivalent to the [relevant SECI configs](https://github.com/ISISComputingGroup/IBEX/wiki/INES-Instrument-Details#ines-seci-configs) exist
- [ ] Confirm IBEX configurations provide synoptics equivalent to SECI config VIs
- [ ] Confirm the correct motor axes / setpoints exist
- [ ] Confirm all sub-tickets are covered:
    - [ ] #3523
    - [ ] #3524
    - [ ] #3525
    - [ ] #3576
    - [ ] #3577
    - [ ] #3579
    - [ ] #3580

**Comment by Alistair-McGann-Tessella** [comment]
Is there a solution for the INES IV front panel? This seems to have a voltage vs current graph and voltage or current ramping which I'm not sure are provided by the current IOC. Do the INES scientists still need these?

**Comment by kjwoodsISIS** [comment]
@Alistair-McGann-Tessella - judging by the list of equipment on the INES wiki page, I guess this graph displays data from the Keithley 2400/2410.  It should be straightforward to display a graph of the relevant PVs in an OPI  (ask Tom - he's done this sort of thing before).

**Comment by Tom-Willemsen** [comment]
Yes - the graph is relatively straightforwards to do in an OPI - but it is work that needs doing. The instron stress rig OPI does this type of plot (allowing you to choose two channels to plot against each other).

The voltage and current ramping is a bit harder. We do have a module that does ramping as part of ReadASCII, but I'm not sure how generic it is (I seem to remember it being very temperature-related rather than generic, but I may be wrong). The other potential solution would be to do the ramping from a Python script.

**Comment by kjwoodsISIS** [comment]
Please check with Antonella first - it may be that she only needs something simple (I believe they don't use the Keithley very often).  I would hate to see us spend a lot of time creating an over-engineered solution.

**Comment by ThomasLohnert** [comment]
They will not use the Keithley before 2019, but did not communicate whether they still require those bits in the OPI. I will put in a ticket and discuss what specifically they want/need when I demonstrate IBEX to them.

**Comment by kjwoodsISIS** [comment]
@ThomasLohnert  & @Alistair-McGann-Tessella 
OK.  If they won't use the Keithley before 2019, what remains in terms of re-work for this ticket?

**Comment by Alistair-McGann-Tessella** [comment]
I think that was the only thing I wasn't sure about, I'd be happy to put this into review completed

**Comment by kjwoodsISIS** [comment]
OK.  If the ticket is ready to be moved to Review Complete, it should be moved.
