### ISSUE TITLE
Muon Separator: Investigate voltage readings

### ISSUE THREAD

**Issue by Rory-Potter-Tessella** [ISISComputingGroup/IBEX#3612]
As a developer, I want a better understanding of the separator voltage signal so that I know what level of signal processing is required to accurately monitor the separator voltage reading.

On the 24th of October, a 0.1uF capacitor was attached to the DAQ to filter out the noise in the signal being fed to the DAQ above 150Hz.

The separator voltage readings are not as we expected. This ticket is an umbrella ticket to investigate voltage readings from the separator.

### Subtickets

- [x] #3767 - Muon Separator: Investigate the effect of averaging on the signal.
- [x] #3768 - Muon Separator: Investigate the effect of averaging on the signal within packets of data.
- [x] #3875 - Muon Separator: Investigate the effect of filtering on spark data
- [x] #3879 - Muon Separator: Investigate if current needs filtering

### Acceptance Criteria

- [ ] A decision has been made on what level of signal processing to implement as part of the separator IOC.
    - ** NOT DONE** Decision will be made separately from this ticket this is just a recommendation

**Comment by Rory-Potter-Tessella** [comment]
I have analysed some of the data we collected from the Separator PSU using the Separator IOC, before Andrew added the 0.1uF capacitor, and compared the raw data against an averaging of the data obtained be averaging pairs of samples which are 180 degrees apart.

Looking at one array of data given to us by the DAQ (0.1 seconds worth of data), we can plot the attached graphs. The noisiness will partly be a reflection of the number of samples (100) and the fact we recorded this data before Andrew installed the capacitor. The “voltage_data_comparison.png” graph shows the raw data plotted against the averaged data while “voltage_data_faceted.png” shows the raw data and averaged data plotted side by side.

![voltage_data_comparison.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b082ed9b62fd1001186134b/125516c66e82c728ace21e0d46fe9b96378384acb0edbe57a562f39b245626612017ac2532c9a138ad4d71040c1b5ca6535d5917aafbdc78a4b53d72895e09ecd26d5f73c23847aeee9003ad43eb7edf10d8eff6df0ed2e22f24ee818e4a3a1f021d8efa5833a59c42da15.png)

![voltage_data_faceted.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b082ed9b62fd1001186134b/125516c66e82c728ace21e0d46fe9b96378384acb0edbe57a562f6952a4333762d46ef696097ec22ba416f43554d4baa120e5d11affb8a2aa4b53e728b5f0bedd6695a22c46b03b0aac04ee155e57dd205d0f4ae805ec1e03724e28f8e483b19001e8afe5535b2d4.png)

Looking at a 10-minute window of data, we see that the standard deviation of the raw data is 0.13123. The standard deviation is reduced to 0.01362 after averaged the data, an 89% decrease.

**Comment by Rory-Potter-Tessella** [comment]
I’ve analysed the new signal over a couple of different time periods: 210 seconds and 600 seconds from Friday 9th of November around 10:46 am.

From analysing 210 seconds of data, the data has a mean of 93.176931kV and a standard deviation of 2.394288kV. The amount of unstable time is 161.87 seconds using stability bounds of 1kV above and below the mean.  After averaging values which are 180 degrees apart, the data has a mean of  93.177028kV and a standard deviation of 0.152311kV, a 93.6386% reduction in the standard deviation. The amount of unstable time reduced to 0.74 seconds, which is a  99.54% decrease in the amount of unstable time.

![210s-raw-voltage](https://user-images.githubusercontent.com/39518146/48490400-3c68d900-e81d-11e8-90b5-46c94650b17c.png)
![210s-averaged-voltage](https://user-images.githubusercontent.com/39518146/48490401-3c68d900-e81d-11e8-84cd-edcdd90e30b7.png)

From analysing 600 seconds of data, the data has a mean of 93.177092kV and a standard deviation of 2.383439kV. The amount of unstable time is 480.55 seconds using stability bounds of 1kV above and below the mean. After averaging values which are 180 degrees apart, the data has a mean of  93.177117kV and a standard deviation of 0.151717kV, a 93.6345% reduction in the standard deviation. The amount of unstable time reduced to 2.07 seconds, which is a  99.56% decrease in the amount of unstable time.

![600s-averaged-voltage](https://user-images.githubusercontent.com/39518146/48490413-425eba00-e81d-11e8-8918-38964e8faae6.png)
![600s-raw-voltage](https://user-images.githubusercontent.com/39518146/48490414-425eba00-e81d-11e8-8e16-2f635f58953f.png)

I have emailed the Muon Instrument scientists the results of this analysis. This ticket is in impeded until we have decided how to proceed.

**Comment by Rory-Potter-Tessella** [comment]
[Pull request](https://github.com/ISISComputingGroup/separator-signal-analysis/pull/2)

**Comment by Rory-Potter-Tessella** [comment]
For the Reviewer:

- [ ] Check that the following conclusions described are correct (explained in notebooks 6,7,8): 
    - To filter out the noise, we need to implement a size 2 moving average filter of the voltage signal. This will not adversy affect our ability to detect sparks in the voltage signal.
    - The current signal does not appear to need any filtering to detect if the signal is stable.
- [ ] Check that the Readme ([pull request](https://github.com/ISISComputingGroup/separator-signal-analysis/pull/5)) describes how to get started and the make file has a suitable set of commands.
- [ ] All sub-tickets have been completed and reviewed.
