### ISSUE TITLE
SURF: Umbrella Ticket for SURF Tickets

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#3746]
I want to keep track of the implementation of all the tickets necessary to migrate SURF to IBEX.
- [x] Requires #3484  (TPG-361 & -362)
- [x] Requires #3742  (Julabo)
- [x] Requires #3745  (Keyence LK-G)
- [ ] ~Requires #3780  (Hitachi HPLC)~
- [x] Requires #3781  (Knauer K-6)
- [x] Requires #3782  (Knauer HPLC)
- [x] Requires #3783  (NIMA Trough)
- [x] Requires #3784  (Thurlby EXP355P)
- [x] Requires #3786  (Watson-Marlow Syringe Pump)
- [x] Requires #3787  (WPI Aladdin Syringe Pump)
- [ ] ~Requires #4456  (Haake N6-C41 Water Bath)~
- [ ] ~Requires #4457  (Grant R5 GR150 Water Bath)~

**Comment by kjwoodsISIS** [comment]
#3780 is no longer required - Hitachi pumps have been withdrawn from service.

**Comment by kjwoodsISIS** [comment]
#4456 and #4457 are no longer required.  Haake & Grant water baths have been withdrawn from service.

**Comment by kjwoodsISIS** [comment]
All tickets complete.  Ticket can be closed.
