### ISSUE TITLE
SANS2D: Control of Vacuum System (EPIC)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4554]
As a SANS2D scientist, I want IBEX to report and control the status of the vacuum system throughout SANS2D, so that I can control my experiments.

#### Acceptance Criteria
1. I can view the status of the vacuum pumps
1. I can view the status of the vacuum gauges
1. I can view & control the status of the fast shutter
1. I can view & control the status of monitor 3
1. I can view the status of valve 8
1. I can view the status of aperture/guide seals
1. I can view & control the status of the guide system
1. I can view/control all of the above equipment via the IBEX GUI
1. I can view/control all of the above equipment via genie_python
1. IBEX provides the same level of functionality as the existing LabVIEW VI

#### Sub-Tickets
- [x] #4555 SANS2D: Vacuum System - document PVs
- [x] #4556 SANS2D: Vacuum System OPI
- [x] #4557 SANS2D: Miscellaneous Controls
- [x] #4558 SANS2D: Vacuum Pump Status Controls
- [x] #4559 SANS2D: Gauge Link Controls
- [x] #4560 SANS2D: Fast Shutter Control
- [x] #4561 SANS2D: Monitor 3 (genie_python)
- [x] #4562 SANS2D: Monitor 3 (GUI)
- [x] #4563 SANS2D: Valve 8 Status
- [x] #4564 SANS2D: Seal Pressure Controls
- [x] #4565 SANS2D: Guide System Controls

#### Notes
1. The Vacuum System applies to both the front-end (Guides & Apertures) and back-end (Vacuum Tank) components of SANS2D.
1. This ticket is an EPIC.  It is not intended that this ticket be tackled as a single piece of work.  Instead, it will be implemented via a series of smaller tickets.
1. With a few exceptions (noted in the tickets listed below), IBEX will *not* directly control the vacuum system.  The vacuum system is controlled by a FINS PLC.  IBEX will determine the state of the vacuum system by reading information from the FINS PLC.  If IBEX needs to change the state of any devices related to the vacuum system, it does so via the PLC.
1. There are schematic diagrams showing the how the [SANS2D vacuum system OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Vacuum_System_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D vacuum is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Vacuum System`  (for more details see the `S2d Vacuum System - Front Panel.vi` in the file `Sans2d Vacuum System - System Functions.llb`)
1. Consult the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document for more information about beamline devices.
1. Consult the [SANS2D_Drawing](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Sans2d_drawing_for%20_IBEX(Sarah%20and%20Najet).pptx) for schematic sketches of SANS2D.

**Comment by John-Holt-Tessella** [comment]
This should be picked up at the same time as #4559, ensure someone else hasn't already picked that up.

**Comment by Tom-Willemsen** [comment]
All sub-tickets now completed.
