### ISSUE TITLE
SANS2D: Control of Aperture & Guides (EPIC)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4568]
As a SANS2D scientist, I want IBEX to control the SANS2D apertures and waveguides, so that I can adjust them for my experiments.

#### Acceptance Criteria
1. I can control all 5 moveable waveguides via the IBEX GUI
1. I can control all 5 moveable apertures via the IBEX GUI
1. I can control all 5 moveable waveguides via genie_python
1. I can control all 5 moveable apertures via genie_python
1. IBEX provides the same level of functionality as the existing LabVIEW VIs

#### Sub-Tickets
- [ ] #nnnn SANS2D: Apertures and Waveguides OPI
- [ ] #nnnn SANS2D: Guides - Vacuum & Motor Status
- [ ] #nnnn SANS2D: Aperture & Waveguide motion - STOP
- [ ] #nnnn SANS2D: Aperture & Waveguide - Positional Error
- [ ] #nnnn SANS2D: Named Aperture & Guides Positions
- [ ] #nnnn SANS2D: Aperture Position Controls
- [ ] #nnnn SANS2D: Waveguide Position Controls

#### Notes
1. This ticket is an EPIC.  It is not intended that this ticket be tackled as a single piece of work.  Instead, it will be implemented via a series of smaller tickets.
1. There are schematic diagrams showing the operation of the [SANS2D apertures and waveguides](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Guides%20and%20Apertures.pptx).
1. There are schematic diagrams showing the how the SANS2D apertures and waveguides [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Waveguide_Advanced_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D apertures and waveguides is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Waveguide` (for more details see the `S2d - Waveguide Front Panel.vi` in the file `Sans2d - Waveguide Motion.llb`)

**Comment by DominicOram** [comment]
Timebox to do 1 day of work now, will decide on which ticket today.

**Comment by DominicOram** [comment]
Timebox for 2 days

**Comment by DominicOram** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/4575 is currently in progress and required for most of these so this can't be picked up until it's merged.

**Comment by John-Holt-Tessella** [comment]
0 points tickets are all in sub tickets
