### ISSUE TITLE
SANS2D: Control of Vacuum Tank (EPIC)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4576]
As a SANS2D scientist, I want IBEX to control the equipment in the SANS2D vacuum tank, so that I can control my experiments.

#### Acceptance Criteria
1. I can control the front beam-stop
1. I can control the front detector
1. I can control the front baffle
1. I can control the rear baffle
1. I can control the rear detector
1. I can control the rear beam-stops
1. I can see when motion of the detectors is enabled/disabled
1. I can control all of the above equipment via the IBEX GUI
1. I can control all of the above equipment via genie_python
1. IBEX provides the same level of functionality as the existing LabVIEW VI

#### Sub-Tickets
- [x] #4577 SANS2D: Vacuum Tank OPI
- [x] #4578 SANS2D: Vacuum Tank - Vacuum Status
- [x] #4579 SANS2D: Vacuum Tank motion - STOP
- [x] #4580 SANS2D: Detector & Baffle Indicator
- [x] #4581 SANS2D: Front Detector Beam Stop
- [x] #4582 SANS2D: Front Detector Strip Beam Stop
- [x] #4583 SANS2D: Rear Detector Beam Stops
- [x] #4584 SANS2D: Rear Detector Strip Beam Stop
- [x] #4585 SANS2D: Baffle Position Controls
- [x] #4586 SANS2D: Detector Position Controls
- [x] #4587 SANS2D: Minimum Baffle/Detector Intervals
~~- [ ] #5499 Move all button~~ no longer required, see comment on https://github.com/ISISComputingGroup/IBEX/issues/5499

#### Notes
1. This ticket is an EPIC.  It is not intended that this ticket be tackled as a single piece of work.  Instead, it will be implemented via a series of smaller tickets.
1. The SANS2D instrument scientists have provided documents describing SANS2D ([Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) and [Sans2d_drawing_for_IBEX](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Sans2d_drawing_for%20_IBEX(Sarah%20and%20Najet).pptx)).
1. There are schematic diagrams showing the operation of the [SANS2D vacuum tank](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D%20Vacuum%20Tank.pptx).
1. There are schematic diagrams showing the how the SANS2D vacuum tank [User OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_OPI.pdf) and [Advanced OPI](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/SANS2D_Tank_Advanced_OPI.pdf) could look.
1. The LabVIEW VI for the SANS2D vacuum tank is located at: `C:\LabVIEW Modules\Instruments\SANS2D\Sans2d Tank`  (for more details see the `S2d Tank - Front Panel.vi` in the file `Sans2d Tank - System Functions.llb`)
1. Consult the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document for additional information about the Vacuum Tank.
1. Consult the [SANS2D_Drawing](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Sans2d_drawing_for%20_IBEX(Sarah%20and%20Najet).pptx) for schematic sketches of SANS2D.

**Comment by DominicOram** [comment]
Timebox to 2 days

**Comment by John-Holt-Tessella** [comment]
Timebox 4 days

**Comment by JamesKingWork** [comment]
PRs:
- https://github.com/ISISComputingGroup/ibex_gui/pull/1143
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/513

See https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/PLCs#omron-fins to start the FINS IOC for the vacuum tanks correctly.

I have also create the configuration branch NDXSANS2D_vacuum. Run the configuration/galils/setupmotors.bat script to set up the sans2D motors. When approving please merge this branch into NDXSANS2D.

**Comment by John-Holt-Tessella** [comment]
All points in subtickets

**Comment by kjwoodsISIS** [comment]
All tickets now complete.  Issue can be closed.
