### ISSUE TITLE
SANS2D: Miscellaneous Beamline Tickets (EPIC)

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#4589]
As a SANS2D scientist, I want IBEX to control and number of beamline devices, so that I can adjust them for my experiments.

#### Acceptance Criteria
1. I can control the fast shutter via the IBEX GUI
1. I can control the fast shutter via via genie_python
1. I can control the scraper aperture via the IBEX GUI
1. I can control the scraper aperture via via genie_python
1. I can define the sample parameters via via genie_python
1. I can monitor the temperature of the detectors in the vacuum tank
1. I can control the "big" jaws in the vacuum tank
1. I can control the portable "little" jaws
1. I can view the status of my detector banks in a live view.
1. IBEX provides the same level of functionality as the existing LabVIEW VIs

#### Sub-Tickets
- [x] #4590 SANS2D: Fast Shutter Commands
- [x] #4591 SANS2D: DO_SANS and DO_TRANS Commands
- [x] #4592 SANS2D: Scraper Aperture
- [x] #4593 ~SANS2D: Sample Parameters~
- [x] #4594 SANS2D: Monitor Detector Temperatures IOC and OPI
- [x] #4595 SANS2D: Control "Big" Jaws
- [x] #4596 SANS2D: Control "Little" Jaws
- [ ] #4608 SANS2D: Live Display
- [ ] #4370 SANS2D & LOQ: IOC and OPI for T-jump Cell
- [ ] #4371 SANS2D: IOC and OPI for Rotating Stirrer Rack
- [ ] #5588 SANS2D: Aperture & Waveguide motion - inhibit on server side
- [ ] #5719 SANS: Sample Changer
   - [ ] #5589 SANS: Common Sample Changer OPI across all SANS Instruments
- [ ] #5790 SANS2D/POLREF: Huber sample stage
- [ ] #5894 SANS2D: collision avoidance: alternative solution for fast deceleration proposal
- [ ] #5869 SANS2D: Guides cannot be homed at the same time
- [ ] #5882 SANS2D: Final commissioning of aperture and guides
- [ ] #5699 SANS2D: migrate user scripts (with scientists)
- [ ] #5890 SANS2D: Create configurations

#### Notes
1. This ticket is an EPIC.  It exists only to provide a convenient way to group and track a number of only loosely related tickets for beamline (as distinct from sample environment) devices.
1. Consult the [Beam_line_descriptors](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Beam_line_descriptors(Sarah%20and%20Najet).docx) document for additional information about the various beamline devices.
1. Consult the [SANS2D_Drawing](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/SANS2D/Sans2d_drawing_for%20_IBEX(Sarah%20and%20Najet).pptx) for schematic sketches of SANS2D.

**Comment by John-Holt-Tessella** [comment]
All subtickets have been pointed, 1hr to check they are all done.

**Comment by John-Holt-Tessella** [comment]
0 points all points in sub tickets

**Comment by KathrynBaker** [comment]
T-Jump cell superseded, sample changer resolved enough, SANS2D is on IBEX
