### ISSUE TITLE
VHD: Solve Issues for VHD

### ISSUE THREAD

**Issue by John-Holt-Tessella** [ISISComputingGroup/IBEX#5437]
There are several issues that we need to think about for the VHD that should be solved and tickets written for them:

1. [x] `C:\Scripts` is currently a user area for scripts what should happen to it, it needs to be persisted through system updates
  1. IBEX script to create directory junction from c:\scripts to the settings vhd. @Tom-Willemsen to do this.
1. [ ] How does an upgrade work in detail
1. [x] What to do with the `labview modules`, currently the ICP is stored in there along with all LVDCOM VIs (see https://github.com/ISISComputingGroup/IBEX/issues/5518)
    1. We (Tom, John, Dom, Kathryn, Freddie) have decided to copy the existing labview modules into the settings VHD in the short term. In the long term we should move the required bits of labview into our ibex build.
1. [ ] There should be an official set of "release" VHDs, this will need a variant of the existing vhd creation job which fills the VHDs with a release build
1. [ ] The settings area is in `c:\instrument\settings\config\ndhspare70` when it should be in `c:\instrument\settings\config\ndx<instrument>`
  * Needs to be in IBEX script
1. [ ] `init_inst_name.py` needs to be renamed to `init_<instrument>.py` (new instrument) / check out appropriate config branch (existing instrument)
  * Needs to be in IBEX script
1. [x] Base image is missing notepad++
  * Just needs installed putting in. @Tom-Willemsen to add (once config files are in git)
1. [x] Base image does install `git` but it is such an old version that it can't auto-update itself (we should install a newer version)
1. [ ] Admin account is created with the wrong password and needs changing
  * @ChrisM-S to change
1. [x] spudulike's password is "expired"
  * Ignore this or if it comes up just set it to the same password again
1. [x] labview is not installed in the base image
1. [x] nport administrator is not installed in the base image
  * Also, how do port settings get carried over on upgrade
1. [x] MySQL service is not installed/started
  * This needs to be put in a script which gets called by MDT
1. [x] `vcruntime140_1.dll` is missing and get an error box during ibex server startup
1. [x] Cannot access the archive as spudulike on the ndx as the "referenced account is currently locked out"
  * @ChrisM-S to look at permissions
1. [x] We want MDT process/config files to be in an accessible git repo
  * It is now accessible (details on passwords page). Once we remove a few large files we can put it in git.
1. [x] `makeinst.cmd` currently has to be manually copied onto the machine, do this via MDT
1. [ ] The `makeinst.cmd` script which maps the VHDs onto their mount points is unreliable and gives confusing errors and/or claims to have worked when it hasn't. We need to make this script more robust and more user-friendly
1. [ ] Register ISISICP
1. [ ] Java should be added to `Apps` VHD and added to path by deploy script so that alarm/log server work
1. [ ] At end of run need a script run to move data see #5902 for details
1. [ ] The windows installation sometimes fails with a bluescreen see https://github.com/ISISComputingGroup/IBEX/issues/5923 for details
[Add issues as they come up to the above]

**Comment by ChrisM-S** [comment]
Note Controls ticket [#679](https://github.com/ISISComputingGroup/ControlsWork/issues/679) gives a source list of things which need to be improved on the System VHD clone, some of these may be related to solutions to the issues which are being listed here.

**Comment by GRyall** [comment]
superseded by #8319. Closing as duplicate.
