### ISSUE TITLE
HTS Magnet: IOC & OPI for HTS Magnet

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5577]
As a scientist I would like to control and monitor the HTS Magnet, so that I can vary the magnetic field in my experiments.

This ticket has been split into 5 sub-tickets:
- [x] Requires #5660	**HTS Magnet - Step 1: New OPI**
- [x] Requires #5661 	**HTS Magnet - Step 2: Implement Ramping in the Kepco IOC**
- [x] Requires #5662 	**HTS Magnet - Step 3: Implement Magnetic Field Controls**
- [x] Requires #5663 	**HTS Magnet - Step 4: Create SmartMonitor IOC**
- [x] Requires #5664	**HTS Magnet - Step 5: Create Details Tab**

#### Acceptance Criteria
1. The OPI provides two tabs: a main tab and a details tab.
   1. the main tab allows control of the power supply and displays key status information
   1. the details tab provides detailed monitoring information (useful to technicians)
1. On the main tab,
   1. IBEX must clearly reflect the magnet power status (`ENERGISED` or `OFF`)
   1. IBEX must clearly reflect the magnet overall status
      * `Magnet is at Room Temperature`
      * `Magnet is cooling down`
      * `Magnet is at Operating Temperature`
      * `A fault has occurred`
      * For the avoidance of doubt there is no status corresponding to `Magnet is warming up`
   1. IBEX must permit control and monitoring of power and field settings
      * IBEX must display the status of the power supply (`ON` or `OFF`)
      * I can switch the power supply `ON` or `OFF`
      * On selecting `OFF`, the magnitude of the current must be decreased to zero using the current ramp rate.
      * IBEX must display the power supply voltage readback as a numerical field (units: V)
      * IBEX must display the power supply current readback as a numerical field (units: A)
      * IBEX must display the power supply voltage readback as a dial (units: V)
      * IBEX must display the power supply voltage readback as a dial (units: A)
      * IBEX must display the magnetic field readback (determined via the calibration file) (units: G)
      * I can switch between two operating modes: `FIELD` mode or `CURRENT` mode
      * In `CURRENT` mode, I can set the current
         * in `CURRENT` mode the current is set directly (no need for a calibration file).
         * `CURRENT` mode will be used to calibrate the magnet and when no suitable calibration file is available.
      * In `FIELD` mode, I can set the magnetic  field
         * the IOC must use the calibration file to determine the appropriate current
      * IBEX must display the current ramp rate readback (units: A/min)
      * I can set the current ramp rate
         * the ramp rate applies equally to increasing or decreasing the current
   1. IBEX must enforce a maximum allowable current (value to be determined)
   1. IBEX must enforce a maximum allowable current ramp rate (value to be determined)
   1. I can select a calibration file to use with the HTS Magnet.
1. On the details tab, IBEX must display information provided by the SmartMonitor
   1. the current values of temperatures T1-T4 (units: K) and voltages V1-V4 (units: V)
   1. the magnet protection limits for temperatures T1-T4 and voltages V1-V4
   1. the safe operating limits for temperatures T1-T4 and voltages V1-V4
   1. a graph of temperatures T1-T4 as a function of time
   1. the current values of temperatures T1-T4 and voltages V1-V4 should be logged
1. I can use genie_python control the PSU.
1. I can use genie_python monitor the HTS magnet.

#### Notes
1. Facts about the HTS Magnet are documented in #5287.
   - HTS = High Temperature Superconductor (110K, I believe)
1. Further information is available in the `Manuals\HTS` folder in the shared directory.
1. The magnet will be shipped to ISIS in September.
1. Scientists wish to commission the magnet in October.
1. From a controls perspective, there are two components we can communicate with:
   1. two KEPCO BOP 6-125MG units which are connected in parallel (one device is slaved to the other, so the two devices appear as one; we need only communicate with one).
   1. a SmartMonitor supplied by the magnet manufacturer.  From our perspective, the SmartMonitor is a read-only device; we can use it to get status information, but we cannot use it to control the magnet.  The only way to control the magnet is by the power supply.  The entire command set of the SmartMonitor consists of 3 commands.
1. Schematics for how the OPI might appear are available:
   - [Main tab](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/HTS_Magnet/HTS_OPI_Schematics_v4_Normal_Tab.pdf)
   - [Details Tab](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/HTS_Magnet/HTS_OPI_Schematics_v4_Details_Tab.pdf)
      * the colour and size of the magnet power status light is deliberate; it needs to be very obvious that the magnet is powered up.
      * the colours of the overall magnet status lights are deliberate; they correspond to coloured LEDs on the SmartMonitor device.
1. The scientists have requested the current & voltage readbacks are displayed as dials (as well as numerical fields) because dials also provide immediate visual feedback that the magnet is powered up.
1. Maximum allowable current and current ramp rates have yet to be determined.  They should be implemented as configurable items (ideally configurable only by support staff).  Scientists and or technicians will provide the agreed maximum allowable current and current ramp rates.
1. The ramp rate is deliberately defined as an absolute value, meaning it applies equally to the rate at which the current is increased.  For example, if the current ramp rate is set to 0.15 A/min and the scientist requests a greater current, the magnitude of the current should be increased in steps of 0.15A/min.  Similarly, if the current ramp rate is set to 0.15 A/min and the scientist requests a lower current, the magnitude of the current should be decreased in steps of 0.15A/min.
1. A suggested ramping algorithm is illustrated in [Ramping.xslx](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/HTS_Magnet/Ramping.xlsx).
1. Additional information from magnet manufacturer in [ICP Discussions - HTS Magnet](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/HTS_Magnet/HTS_Magnet_Answers_2020_09_03.pdf).

**Comment by JamesKingWork** [comment]
For POLREF but will be used on other refl and SANS

**Comment by JamesKingWork** [comment]
We need to test magnet before commissioning in October

**Comment by kjwoodsISIS** [comment]
If desired, this ticket could be implemented as 5 sub-tickets:
1. Create a new OPI to work with existing Kepco IOC
   * using the [sketch of the main tab](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/HTS_Magnet/HTS_OPI_Schematics_v4_Normal_Tab.pdf) of the OPI, create a new OPI with empty group boxes
   * populate the Power & Field group box with controls, leave the others empty for now
     - the Power LED, Power On/Off switch, current & voltage fields (readback & setpoint) and current & voltage gauges (readbacks) can be hooked up to the Kepco IOC.
     - the other controls in the Power & Field group box can remain inactive for now.
   * test with Kepco emulator
1. Implement ramping in the Kepco IOC 
   * extend the Kepco IOC to support ramping
      - may need to extend the emulator too
   * make the maximum current & maximum ramp rate configurable; set them to placeholder values for now (e.g. maximum current = 5A, maximum ramp rate = 0.5A/min)
   * activate the Ramp Control group in the OPI
   * test with Kepco emulator
1. Activate Field controls 
   * activate operating mode - toggle between `Current` and `Field` modes.
   * populate & activate the Calibration group
      - create a dummy calibration file for testing purposes
   * activate the Field controls
   * test that selecting a field value sets the appropriate current
1. Create a SmartMonitor IOC 
   * The SmartMonitor monitors the magnet.
   * Create a SmartMonitor IOC & emulator
      - From an IBEX perspective, the SmartMonitor is a read-only device.  It is very simple.  It has only 3 commands.
   * populate and activate the Magnet Status group in the OPI
   * test with Kepco & SmartMonitor emulators
1. Add Advanced Tab to OPI
   * using [the sketch](http://www.facilities.rl.ac.uk/isis/computing/ICPdiscussions/HTS_Magnet/HTS_OPI_Schematics_v4_Details_Tab.pdf), create the Advanced tab of the OPI
      - all the fields are read-only values provided by the SmartMonitor.

**Comment by kjwoodsISIS** [comment]
> From: Instrument Scientist
> Sent: 20 August 2020 13:00
> Subject: RE: News on HTS Magnet?
> 
> Hi, Yes so far it’s still on track for delivery at the end of September. 
> We may not be able to test it online due to the issue of machine shop time 
> for making the plates but I will keep you posted.
>
> We should be able to plug it in on the side and test it though.
