### ISSUE TITLE
SANS2D: Test Coordinated Aperture and Guides

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5881]
As a SANS2D instrument scientist I would like to be able to set the aperture and guides as a group. The basic commissioning of them was done in https://github.com/ISISComputingGroup/IBEX/issues/5836 and so the axes all work but the following need to be tested:
- [ ] #4569 SANS2D: Apertures and Waveguides OPI
- [ ] #4570 SANS2D: Guides - Vacuum & Motor Status
- [ ] #4571 SANS2D: Aperture & Waveguide motion - STOP
- [ ] #4572 SANS2D: Aperture & Waveguide - Positional Error
- [ ] #4573 SANS2D: Named Aperture & Guides Positions
- [ ] #5869 Guides cannot be homed at the same time

During the first round of testing there was also issues with the guides stalling. We should do some soak testing to make sure they are not stalling more in IBEX than SECI.
