### ISSUE TITLE
SANS2D: Final commissioning of aperture and guides

### ISSUE THREAD

**Issue by DominicOram** [ISISComputingGroup/IBEX#5882]
As a SANS2D instrument scientist I would like to be able to set the aperture and guides as a group. The basic commissioning of them was done in https://github.com/ISISComputingGroup/IBEX/issues/5836 and so the axes all work but the following need to be tested:
- [x] #4569 SANS2D: Apertures and Waveguides OPI
- [x] #4570 SANS2D: Guides - Vacuum & Motor Status
- [x] #4571 SANS2D: Aperture & Waveguide motion - STOP
- [x] #4572 SANS2D: Aperture & Waveguide - Positional Error
- [x] #4573 SANS2D: Named Aperture & Guides Positions
- [x] #5869 Guides cannot be homed at the same time

During the first round of testing there was also issues with the guides stalling. We should do some soak testing to make sure they are not stalling more in IBEX than SECI.

## Acceptance Criteria
- [x] The above have been tested on SANS2D and the scientists are happy

**Comment by rerpha** [comment]
I am doing this during this week so I'll point at the end as to how long it took. Guides are working, homing doesn't ever need to be done again as they're servo motors with rotary + linear encoders.

**Comment by rerpha** [comment]
Somewhat surprisingly motionsetpoints seems to work between a Galil + Beckhoff despite only being loaded in by the former.

**Comment by rerpha** [comment]
One thing I noticed yesterday that the scientists said they didnt like was that the vacuum status shows "deflated" even though it's not, just because there is a difference in the two pressure readings. Scientist suggested having some sort of tolerance

**Comment by rerpha** [comment]
Motion setpoints have been set up, they are working well, scientist is happy!

**Comment by rerpha** [comment]
Only thing that remains is the signal to enable after vacuum permit lost, but I will do this as a support ticket as its just a beckhoff workaround for now - solution for this needs to be discussed with scientists on Monday.

**Comment by SamJenkins1** [comment]
According to Jack everything appears to be all working on this.
