### ISSUE TITLE
MuSR: Umbrella Ticket

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#5960]
I want to keep track of the implementation of all the tickets necessary to migrate MuSR to IBEX.
- [x] Requires #5178 MuSR: Rotation change investigation
- [x] Requires #5096 MuSR: IOC & OPI to control Instrument Rotation
- [x] Requires #5099 MuSR: Transverse Field PSU
- [x] Requires #5949 MuSR: More Kepco IOCs
- [x] Requires #5949 MuSR: Steering OPI
- [x] Requires #5950 MuSR: Lakeshore 340 - Investigate Excitation Feature
- [ ] Requires #5959 MuSR: 3He Refrigerator Investigation
- [x] Requires #5956 MuSR: King Fridge Configuration
- [x] Requires #5957 MuSR: uDR3 & uDR4 Fridge Configurations
- [x] Requires #5958 MuSR: Dual ITC-503 OPI and Configuration
- [x] Requires #5971 MuSR: Migrate to IBEX
- [x] Requires #5990 MuSR: MuSR: Danfysik - Slew Rate

**Comment by JamesKingWork** [comment]
3He Refrigerator tickets managed at https://github.com/ISISComputingGroup/IBEX/issues/6247. MuSR ticket management now in https://github.com/ISISComputingGroup/IBEX/projects/9.
