### ISSUE TITLE
RIKEN: Umbrella Ticket

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6107]
I want to keep track of the implementation of all the tickets necessary to support the refurbishment of the RIKEN beamline.
The following IOCs and OPIS are expected to run on the RIKENFE instance of IBEX.  they will be used to monitor the RIKEN beamline.

- [ ] Requires #5431	RIKEN: Solenoid PSU
- [ ] Requires #5871	RIKEN: IOC & OPI for Danfysik 9700
- [ ] Requires #5872	RIKEN: Custom Magnet PSU ("synoptic") OPI
- [ ] Requires #5873	RIKEN: Custom PSU Tabular Summary OPI
- [ ] Requires #5874	RIKEN: IOC & OPI for Technix PSU
- [ ] Requires #5875	RIKEN: IOC & OPI for Kicker Timing
- [ ] Requires #5876	RIKEN: OPI for Kicker & Separator HV
- [ ] Requires #5877	RIKEN: Extend TPG300 IOC & OPI
- [ ] Requires #5878	RIKEN: Custom Vacuum ("synoptic") OPI
- [ ] Requires #5976	RIKENFE: Test new Danfysik power supplies when they arrive in R6

See also the following related tickets:
- [ ] #5879	ARGUS: Magnet Status OPI
- [ ]  #5880	CHRONUS: Magnet Status OPI
- [ ]  #5997	Handover: RIKEN Beamline

**Comment by KathrynBaker** [comment]
Well and truly done in every practical manner
