### ISSUE TITLE
VHD deployment: part 1: basic windows installation

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/IBEX#6121]
As a developer I would like to be able to build a windows platform in an automated way.

### Acceptance criteria

To be done as part of this ticket:
- [x] Fix bluescreen issue from #5923
- [x] Finish review of #5923
- [x] Make MDT config files into a git repository
- [x] Tidy up directory structure of MDT configuration files
    * Remove unneeded files
 - [ ] ~Create a jenkins job which runs MDT from the files in git and proves that the build is successful~ - moved into https://github.com/ISISComputingGroup/IBEX/issues/6317 

### Notes

- @ChrisM-S believes share paths are crossed (i.e. that DEV deployment share is pointing at PROD or vice-versa) and that this is the cause of the windows bluescreen issue.

**Comment by rerpha** [comment]
So far I have spent some time trying to fix/workaround the bluescreen issue. It looks like the solution is to start the MDT install without the VHDs attached, then attach them and run `make_inst.cmd`. I have updated the docs to reflect this. Currently putting the MDT deployment share into a git repository, but it's taking a while as the folders are so large.

**Comment by rerpha** [comment]
ok, to recap what i've done so far:

- Bluescreen issue has been worked around - attaching the VHDs afterwards seemed to sort this out. 
  - Other than labview the VHD created by MDT installs IBEX as normal, then the VHDs can be mounted after installation
- MDT configs (.wim files) have been stored in a private git repository
- .svn folders have been removed on the mdt server area
- a .gitignore has been used to ignore .iso files and similar 

What's blocking me at the minute when trying to push the rest of the config files is that the shared area seems to have run out of space? I am getting this: 
```
remote: fatal: write error: No space left on device
fatal: sha1 file '<stdout>' write error: Broken pipe
error: remote unpack failed: index-pack abnormal exit
To <hidden>mdt_config.git

```

I still need to create and run the jenkins job as well.

**Comment by rerpha** [comment]
Have now added all files except for dev1\MDTDeploymentShare\Applications as trying to `git add` them doesn't work - I have a feeling they don't need to be added as they'll be packaged in the `.wim` file

Again, still need to do the jenkinsfile

**Comment by rerpha** [comment]
OK, having mounted the VHDs after the install, and then doing this: 
```
C:\volumes>mklink /J "Apps" "E:\"
Junction created for Apps <<===>> E:\

C:\volumes>mklink /J "Var" "G:\"
Junction created for Var <<===>> G:\
```

I haven't attached a "Data" or "Scratch" VHD, but I guess those are just blank VHDs anyway, so in theory it should work? Will update the build instructions now to reflect what i've done as it appears to be starting up everything needed

**Comment by rerpha** [comment]
just adding the updated config into git now. I believe the bulk of this ticket is done and we have found a way to get a basic windows installation through MDT that does not bluescreen by tidying up the MDT shares. 

For the next ticket Java will need to be installed correctly (currently disabled in the task sequence) as the IOC logger is complaining. Sophos also doesn't look happy. 

Last bit of work for this ticket is to re-add everything to git, push it, then write a Jenkins job that spins up a machine from the .iso from git then pings it, then shuts it down. As we only care about a basic windows installation we don't need to run any other tests at the moment, or at least any that aren't testing windows is installed.

**Comment by rerpha** [comment]
In fact, i am going to spin the jenkins job off into a new ticket, rather than repointing this one.

**Comment by rerpha** [comment]
To review: 

- Check that at the very least an .iso image is stored in the new private git repository
- Test that following [this page on the wiki](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Building-a-windows-10-instrument-machine-from-MDT) works and fulfils the acceptance criteria (or check it makes sense, there is an example called NDXMDTINST1 running on SPARE80

**Comment by ChrisM-S** [comment]
Just a note, the decision was I believe to keep the Java installation as part of the IBEX install rather than install into Windows 10.  The commented out one was when I was expecting Java to be part of the base platform.

**Comment by rerpha** [comment]
Hmm. I think it may need to be picked up from PATH, so we should consider that for #6123

**Comment by rerpha** [comment]
Release notes: https://github.com/ISISComputingGroup/IBEX/pull/6322
