### ISSUE TITLE
VHD Deployment: Umbrella Ticket

### ISSUE THREAD

**Issue by kjwoodsISIS** [ISISComputingGroup/IBEX#6127]
I want to keep track of the implementation of all the VHD deployment tickets.

#### Part 1: Basic Windows Installation
   - Create a windows platform in an automated way
      - [ ] Requires #6121 VHD deployment: part 1: basic windows installation

#### Part 2: Install Supporting Environment
   - Install the applications & utilities that comprise the supporting environment at ISIS (e.g. Notepad++, NPort, LabVIEW, etc.)
      - [ ] Requires #6122 VHD deployment: part 2a: document how to install and upgrade the supporting environment 
      - [ ] Requires #6123 VHD deployment: part 2: automated install and upgrade for the supporting environment

#### Part 3: Install IBEX
   - Install IBEX and its dependencies (e.g. Java, MySQL, Python, etc.)
      - [ ] Requires #6124 VHD deployment: part 3: automated install and upgrade of IBEX

#### Part 4: Image Configuration
   - Configure a generic image to make an instrument specific image (i.e. how do we create an image that can be deployed to and used on a specific instrument (e.g. how do we turn `NDX<generic>` into `NDXIMAT`, `NDLARMOR`, etc.))
      - [ ] Requires #6125 VHD deployment: part 4a: document how to turn a generic windows image into a specific instrument machine #
      - [ ] Requires #6126 VHD deployment: part 4: automate instrument configuration

 #### Notes
 1. It is likely that as we make progress we realise that we need more tickets in addition to the original set: #6121 - #6126.  Simply create new tickets as required and add them to appropriate part of the process.

**Comment by ChrisM-S** [comment]
Added a link to part three to reflect the potential quick win of using the IBEX built VHD as a deployment mechanizm for IBEX to existing systems which avoids individual file copying and also allows a quick back-out (by replacing the older VHD if a reversion is needed).  See ticket #8319 for detail.
