### ISSUE TITLE
MuSR: 3He Refrigerator Implementation

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#6247]
As a developer, I would like to make sure that I don't miss anything in the implementation of the 3He Refrigerator in IBEX.

There are multiple tickets associated, and once all are complete, this ticket is also complete:

- [ ] Initial Investigation: #5959
- [ ] Document VI control logic: #6239
- [ ] Implement control logic: #6240
- [ ] Communications: #6241
- [ ] OPI: #6244
- [ ] Machine setup: #6242
- [ ] Testing on Device: #6243
