### ISSUE TITLE
Move to using VS2019 builds

### ISSUE THREAD

**Issue by FreddieAkeroyd** [ISISComputingGroup/IBEX#6753]
As a developer I would like to use VS2019 for EPICS. The reason for keeping to 2010 was for galil compatibility. The following strategy should help with the move to VS2019 and swapping between galil builds

Stage 1 - separate galil builds

- [ ] Standardise on VS2019 as default group compiler (VS2022 is not due until November)
- [ ] Upgrade ndw1757 from vs2017 -> vs2019
- [ ] Add epics visual C compile defines (_WIN32_WINNT etc) to target Windows 7 #6724
- [ ] Remove link time code optimisation flag (for portability)
- [ ] Keep EPICS-galil repository as is for now, consider fork of upstream later
- [ ] branch current master to an "oldgalil" branch in EPICS-galil, merge new galil to master, updatew configure/RELEASE of oldgalil #2830
- [ ] support/galil checks out master, support/gail-old "oldgalil" of EPICS-galil
- [ ] branch current master as "oldgalil", update its configure/RELEASE to use support/galil-old, merge newgalil branch of EPICS-ioc to master #2830
- [ ] ndw1757 now builds all this (it can build support/galil-old, db files will get used by stage 2 below)
- [ ] ndhspare53 (visual studio10) checks out "oldgalil" of EPICS-ioc and then builds all except support/galil

Stage 2 - deploy old galil with new

- [ ] use "dllcopy" onm ndhspare53 to put all required dlls for ioc/master/GALIL into its bin directory (we could use a static build, but we haven't tested this widely, so safer to copy DLLs)
- [ ] could deploy  ioc/master/GALIL somewhere to be picked by other builkds, or just deply all EPICS
- [ ] ndw1757 vs2019 build copies in a VS2010 ndhspare53 build to ioc/master/GALILOLD
- [ ] on an instrument swap between galil drivers by renaming ioc/master/GALIL to GALILNEW and GALILOLD to GALIL
