### ISSUE TITLE
Muon "RF": Specific equipment control for items in the RF ranges tasks

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#7370]
As someone using IBEX on the Muon instruments I want to be able to use the suite of "RF equipment" to undertake experiments.

## Acceptance Criteria
- [x] Requirements for component sharing and saving and restoring device settings are refined (#7369)
- [x] There is an IOC to interact with the DG645
- [x] New OPI for the DG645 is created (#7367)
- [x] There are three DG645 IOCs (#7366)
- [x] There are 3 IOCs to control the Aeroflex Signal Generators (#6079)
- [x] The capture of images from oscilloscopes has been explored (#7318)
- The storing of images and raw data from oscilliscopes is available (see also #6084) - being done via waveforms in blocks
- The interaction with the amplifiers is designed (#7368) - with the use of the DIO in question this was not needed
- [x] Design of appropriate way to share components between instruments (#7389)
- [x] Design of appropriate way to save and restore settings for devices which vary by experiment (#7393)
- [x] Implementation of sharing components between instruments (#7515)
- [ ] Generate folder and XML for saving and restoring PVs (#7854)
- [ ] Update blockserver for saving and restoring PVs (#7855)
- [ ] Add GUI aspects for saving and restoring PVs (#7856)

## Notes
- This umbrella ticket supersedes any created before September 2022, it has come out of discussions with the instrument scientists (see #7298 for the initial work), this covers the work to be done moving forwards rather than a wiki page, as a wiki page would not be detailed enough at this time
- RF is often used in quotes as that is a handy label for the equipment, but is isn't always used in RF experiments
- There are a number of design tickets which can be estimated now, and they will generate implementation tickets afterwards which can then be estimated later
- The remaining two design tickets will be generated after further discussion with the instrument scientists as scope and behaviour are not yet understood
- This was edited to reflect the priority order of the tasks post the meeting for #7369, however if ready lower priorities should be completed first. For example, the amplifier interaction requires input from multiple divisions, whilst the following two are entirely within IBEX

**Comment by KathrynBaker** [comment]
Talking with ISs - for the scope want to be able to select and store raw traces as well as pictures from the scope

**Comment by KathrynBaker** [comment]
The key device settings for this equipment were handled in a different way to the plans above in the end as there were other alternatives. The save/restore via XML may become handy in the future, it will be added to our list, a new umbrella ticket created and the sub-tickets renamed.
