### ISSUE TITLE
System Tests: Automate manual system tests using Squish

### ISSUE THREAD

**Issue by NikolaRoev** [ISISComputingGroup/IBEX#7709]
Follows on from https://github.com/ISISComputingGroup/IBEX/issues/7660.

### Acceptance Criteria
- [ ] Squish Test: Script name autocomplete
- [ ] Squish Test: GeniePython DAE script test
- [ ] Squish Test: GeniePython blocks script test
- [ ] Squish Test: waitfor_move motor function
- [ ] Squish Test: Reset layout
- [ ] Squish Test: Refresh PVs stress test
- [ ] Squish Test: Alarms button
- [ ] Squish Test: Alarms tree
- [ ] Squish Test: MCR news
- [ ] Squish Test: Beam information
- [ ] Squish Test: Experiment setup disabled correctly during run
- [ ] Squish Test: Run summary log filter
- [ ] Squish Test: Experiment setup general
- [ ] Squish Test: Spectra plot mode
- [ ] Squish Test: Experiment setup period types
- [ ] Squish Test: Missing experiment setup files
- [ ] Squish Test: Title and Users PV value
- [ ] Squish Test: Incorrect RB number
- [ ] Squish Test: Correct RB number
- [ ] Squish Test: Experiment details parameters
- [ ] Squish Test: Experiment details consistent between client instances
- [ ] Squish Test: Refactor and extend experiment details name tests
- [ ] Squish Test: IOC log filtering
- [ ] Squish Test: IOC log stress test
- [ ] Squish Test: Log Plotter instructions display
- [ ] Squish Test: Motor perspective general
- [ ] Squish Test: Motor OPI behaviour
- [ ] Squish Test: Block functionality in Scripting
- [ ] Squish Test: Run behaviour in Scripting
- [ ] Squish Test: Open OPI from Synoptic element
- [ ] Squish Test: Web Links work correctly
- [ ] Squish Test: Configuration naming restrictions
- [ ] Squish Test: Adding IOCs to configuration behaviour
- [ ] Squish Test: Changes to configuration need to be explicitly saved before taking effect
- [ ] Squish Test: PV search when adding block
- [ ] Squish Test: Verify new block logging default settings
- [ ] Squish Test: Can change block default run-control limits
- [ ] Squish Test: Can change block run-control state
- [ ] Squish Test: Can change block logging state
- [ ] Squish Test: Can remove block from group
- [ ] Squish Test: Can remove group
- [ ] Squish Test: Save new configuration as component
- [ ] Squish Test: Editing component in a configuration
- [ ] Squish Test: IOC added to configuration correctly
- [ ] Squish Test: Can delete multiple configurations simultaneously
- [ ] Squish Test: Can't replace current configuration
- [ ] Squish Test: Loading configuration stops IOCs not in that configuration
- [ ] Squish Test: Can change IOC state in configuration
- [ ] Squish Test: Component IOC settings are consistent when component added to configuration
- [ ] Squish Test: Servers restart behaviour is correct
- [ ] Squish Test: Can delete block
- [ ] Squish Test: Configuration default synoptic behaviour
- [ ] Squish Test: Verify synoptic naming restrictions
- [ ] Squish Test: Changing synoptic component target resets values to default
- [ ] Squish Test: Add PV to synoptic component
- [ ] Squish Test: Synoptic components copy behaviour
- [ ] Squish Test: Synoptic components delete behaviour
- [ ] Squish Test: Can change synoptic component details
- [ ] Squish Test: Synoptic component icon behaviour
- [ ] Squish Test: Synoptic edit dialogue "Clear" button
- [ ] Squish Test: Can edit synoptic save using "Save As"
- [ ] Squish Test: IOC restart behaviour
- [ ] Squish Test: Can restore configuration values in run-control
- [ ] Squish Test: 
- [ ] Squish Test: 
- [ ] Squish Test: 
- [ ] Squish Test: 

### Extra Information
Helpful Squish documentation:
https://doc.qt.io/squish/squish-api.html
https://doc.qt.io/squish/java-convenience-api.html
https://doc.qt.io/squish/tester-created-special-functions.html
