### ISSUE TITLE
Save and Restore Device Settings

### ISSUE THREAD

**Issue by KathrynBaker** [ISISComputingGroup/IBEX#8161]
As someone using devices in different configurations that should be component agnostic I want a way to save and restore sets of PVs.

This is a user story which has come from #7370, a different solution was able to be used there, but the design etc. should not be lost as it is still valid.

- [x] Design of appropriate way to save and restore settings for devices which vary by experiment (#7393) - This was completed within that previous ticket
- [ ] Generate folder and XML for saving and restoring PVs (#7854)
- [ ] Update blockserver for saving and restoring PVs (#7855)
- [ ] Add GUI aspects for saving and restoring PVs (#7856)

**Comment by GRyall** [comment]
Functionality for save and restoring motor positions for reflectometers is still a requirement and would have saved some support time today restoring a database backup to get values. likewise reflectometers tell us save and restore DAE settings would be of use to them as well.

**Comment by Tom-Willemsen** [comment]
To cater for the reflectometer position restore use-case, we need to carefully separate restoring positions by _moving_ to that position, versus restoring a position by _redefining_ the current state as the saved position. Both modes can be useful.

Alternatively the reflectometer _redefinition_ use-case could be served by a standalone script, leaving this complexity out of the generic save/restore (this ticket).

**Comment by KathrynBaker** [comment]
As Tom says, this is about going to a position not redefining a current position, this would not solve the issue with lost positions because a Galil is restarted, I would not be keen to add that complexity to this ticket which we discussed at length, got a plan for, and just haven't had the resource to enact it since we came up with the plan.

**Comment by GRyall** [comment]
Ok, my mistake - do we have a ticket yet about restoring lost positions?

**Comment by Tom-Willemsen** [comment]
https://github.com/ISISComputingGroup/IBEX/issues/5311 is one such ticket (it talks about getting the positions from archive/autosave rather than an explicit save file, but we could provide both options).
