### ISSUE TITLE
Hydrogen Lab R79: migration to IBEX

### ISSUE THREAD

**Issue by GRyall** [ISISComputingGroup/IBEX#8581]
# Issue Description

As a scientist using the R79  Hydrogen Lab, I would like to be able to:
- [ ] migrate my experiment control from using open-genie to genie-python on the two control boxes
- [ ] control my new furnace 
- [x] Control existing items plugged into existing moxa boxes from within Ibex 
- [ ] Control mass spectrometer

Additionally
- [x] VMs are listed in relevant places to ensure they receive patches and updates
- [ ] Set up is documented

### How & Where?
The above will required the setting up of 2 new NDX boxes (the lab is roughly split in half with work happening independently in each half). @ChrisM-S has plans for this. @GRyall can provide contact details for the relevant scientist.

### Additional Information

<sub>What else do I need to know before starting?</sub>

- _Where required files/links are_
- _Describe any potential difficulties with this ticket_
- _Provide links to tickets that must be completed before starting_
- _Provide any images that would be relevant to the ticket_

<sub>_If not applicable, write "Not applicable"_</sub>

[comment]: <> (FILL IN BELOW)
> ...

<sub>See our [Git Workflow](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-workflow#development-work).</sub>

# Acceptance Criteria
<sub>What is the acceptance criteria of this ticket? What should the reviewer expect to be complete?</sub>
- _Define specific conditions that must be met for the issue to be considered complete_
- _Use bullet points for clarity_
- _Ensure each criterion is unique, testable and verifiable_

[comment]: <> (FILL IN BELOW)
> ...

# How to Review
<sub>Before making a PR... </sub>
- _Provide verbose instructions for the reviewer to test that your changes work and fix the issue_
- _Describe if/how you have implemented testing for this issue_
- _Provide screenshots of the feature to help the reviewer if relevant_

<sub>_If not applicable, write "Not applicable"_</sub>

[comment]: <> (FILL IN BELOW)
> ...

<sub>**To the reviewer: Make sure to [update submodules](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Git-workflow#reviewing-work-for-the-submodules-of-epics)!** </sub>

## Planning
04/02/2026 - 00:13:30

**Comment by Tom-Willemsen** [comment]
Some representative GCL scripts in `\\isis\shares\ISIS_Experiment_Controls\data for tickets\Ticket8581_hydrogen_lab`

**Comment by Tom-Willemsen** [comment]
Post-clone tasks (done):
- IBEX deploy
- Add to inst list https://github.com/ISISComputingGroup/EPICS-inst_servers/pull/455
- Add to ansible inventory https://github.com/ISISComputingGroup/ansible-playbooks/pull/39
- Deploy credentials/scheduled tasks (using existing ansible script)
- SSH keys deployed (using existing ansible script)
- Updated notepad++ as clone version has security vulnerability (using existing ansible script)
- VNC server on HYDROGEN1 wasn't allowing `spudulike` logon as `All Users` group was not in VNC config
- `spudulike` added to `OpenSSH Users` group
- Delete settings dirs which had accidentally been copied from SXD/NDHSPARE
- Common config dir looked to be broken - redeployed
- `git config --global --add safe.directory /c/volumes/settings/config/common`
- Allow various IBEX programs through firewall
- Set display resolution to 1920x1080 through windows display settings
- Show hidden files & file extensions
- VNC was timing out (https://github.com/ISISComputingGroup/ControlsWork/pull/857)
- Install machines in hydrogen lab
- Give access to machines to relevant people in Keeper
- Talk to relevant 'fixed' kit (Eurotherms/CCDs/etc)

To investigate:
- Machines not visible from web dashboard, maybe needs adjustment to site CA gateway?
- ISISDAE/ICP not starting with DCOM errors (not critical for hydrogen machines)
- https://github.com/isisComputingGroup/ibex/issues/2196
- https://github.com/ISISComputingGroup/EPICS-ioc/pull/960

**Comment by Tom-Willemsen** [comment]
Mass spec software has been installed by manufacturer on the **NDX**. This is not software that we can self-install - it requires a license key etc to install.

Communication has been confirmed to work via Moxa (it's a standard RS232 connection, 115200/8/None). This eliminates the previous USB-serial adapters. A command the hardware replies to is `help\r`.

**Comment by FreddieAkeroyd** [comment]
Worth checking if either of the solutions mentioned in https://github.com/ISISNeutronMuon/ISISICP/blob/949884f43d6241736af2553de970d2b9cc0bf800/labview%20modules/DAE/README_isisicp_reg.txt help

**Comment by FreddieAkeroyd** [comment]
BTW is NDX machine a 2025 server? In which case we may see some oddities as we've usually ran on desktop builds

**Comment by Tom-Willemsen** [comment]
It is:
> OS Name:                       Microsoft Windows Server 2025 Standard
> OS Version:                    10.0.26100 N/A Build 26100

I did try adding `spudulike` to "DCOM Users" group which didn't seem to help.

**Comment by Tom-Willemsen** [comment]
Nanodac now talking, but unclear how previous system set temperature - no control loops were configured on the nanodac which I was expecting. The old `.vi` is a compiled LabVIEW `.exe` (not running in the LabVIEW IDE) so not trivial to see what it's doing without access to the source code. Possible it had implemented a PID in software...?

**Comment by KathrynBaker** [comment]
I don't think we were involved in that nanodac to begin with, we use read only for the IBEX nanodac because of things being on a wider network and the use of the initial one we had that needed to be used in IBEX, so haven't implemented any control.

**Comment by Tom-Willemsen** [comment]
I'm told Gareth Howells wrote the LabVIEW for the hydrogen lab at the time.

As far as the IOC: we do have control implemented in the IOC which we inherited from ORNL - the IOC has PVs for read & [write](https://github.com/ISISComputingGroup/EPICS-nanodac/blob/master/eurothermApp/Db/nanodac_loop_main.template#L287) on the temperature control loops for example. But do you mean the device itself was set to read-only mode in ZOOM's case? I don't think that's the case for the Hydrogen lab one; looked to be set to read-write from the menus on the device.

**Comment by Tom-Willemsen** [comment]
Nanodac was using an "advanced loop" which required "logging in" to the nanodac to see it on the front panel. Being controlled adequately after https://github.com/isisComputingGroup/ibex/issues/8959 .

There are a small tail of issues/queries still coming in from the scientists, but I think all of the acceptance criteria of this ticket have now been sufficiently met that it's no longer worth keeping this ticket 'in progress'.

PR for documenting this setup: https://github.com/ISISComputingGroup/ibex_developers_manual/pull/208
